apiVersion: v1
kind: Namespace
metadata:
  name: egress-test
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-egress-test
  namespace: egress-test
spec:
  imagePullSecrets:
    - name: registry-credential
  containers:
    - name: test
      image: private-c0978417-kr1-registry.container.nhncloud.com/ta-sgh-ncr/pod-egress-test:1.0.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 365d"]
  restartPolicy: Never
